title: "Frentzen"
description: "Security notes & write-ups"
url: "https://frentzen.github.io"
baseurl: ""               # user site
permalink: /:year/:month/:day/:title/
timezone: Asia/Dubai
show_excerpts: true       # home lists excerpts
minima:
  date_format: "%b %d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/frentzen" }
    - { platform: x,       user_url: "https://x.com/FrentzenAmaral" }
    - { platform: linkedin,user url: "https://www.linkedin.com/in/frentzen-amaral"}
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate       # pagination on home
paginate: 7               # posts per page
paginate_path: "/blog/page:num/"
markdown: kramdown
highlighter: rouge
rouge:
  theme: github
